export const SET_USER_DATA: string = 'SET_USER_DATA';
export const SET_USER_AUTHENTICATED: string = 'SET_USER_AUTHENTICATED';

export const ADD_USER_PROFILE_IMG: string = 'ADD_USER_PROFILE_IMG';
export const GET_USER_PROFILE_IMG: string = 'GET_USER_PROFILE_IMG';
export const SET_USER_PROFILE_DETAILS: string = 'SET_USER_PROFILE_DETAILS';
export const SET_USER_CONTACT_PROFILE: string = 'SET_USER_CONTACT_PROFILE';

export const GET_USER_CLIENT_IMAGES: string = 'GET_USER_CLIENT_IMAGES';
export const SET_USER_CLIENT_IMAGES: string = 'SET_USER_CLIENT_IMAGES';