export const GET_USER_JOBS = 'GET_USER_JOBS';
export const UPDATE_JOB = 'UPDATE_JOB';
export const ADD_JOB = 'ADD_JOB';
export const DELETE_JOB = 'DELETE_JOB';

export const SET_ALL_ACTIVE_JOBS = 'SET_ALL_ACTIVE_JOBS'

export const SET_ARTISTS_JOB_BIDS = 'SET_ARTISTS_JOB_BIDS'
export const ADD_ARTISTS_JOB_BID = 'ADD_ARTISTS_JOB_BID'

export const SET_CLIENTS_JOB_BIDS = 'SET_CLIENTS_JOB_BIDS'
export const ADD_CLIENTS_JOB_BID = 'ADD_CLIENTS_JOB_BID'
